target_column: 'target'
data_path: '../data/herg_data/'
dataset_name: 'herg_ecfp_linear'
num_splits: 10
num_bins: 10
models_path: '../results/gt_synthetic_data/'
configs_path: '../config/gt_herg_data_linear/'
save_path:  '../results/gt_synthetic_data/'